# Generated by Django 5.0.3 on 2024-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
