# Generated by Django 5.0.3 on 2024-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_vendor_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="specifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
