# Generated by Django 5.0.3 on 2024-03-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_products_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="tags",
        ),
        migrations.AddField(
            model_name="products",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.vendor",
            ),
        ),
    ]
