# Generated by Django 5.0.3 on 2024-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_products_tags_products_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(upload_to="category"),
        ),
    ]
