# Generated by Django 5.0.3 on 2024-03-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="core.vendor",
            ),
        ),
    ]
