# Generated by Django 5.0.3 on 2024-03-08 06:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_vendor_created_at_vendor_date_vendor_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path
            ),
        ),
    ]
