# Generated by Django 5.0.3 on 2024-03-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_vendor_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="type",
            field=models.CharField(default="Organic", max_length=100),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_images",
                to="core.products",
            ),
        ),
    ]
