# Generated by Django 5.0.3 on 2024-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_products_type_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="expriry",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="products",
            name="mfd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="stock_count",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
