# Generated by Django 5.0.3 on 2024-03-15 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_products_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="contact",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("proccessing", "Proccessing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="proccessing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="core.products",
            ),
        ),
    ]
